# Generated by Django 6.0.8 on 2026-09-25 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_logs', '0002_patientactivitylog_delete_patientlog'),
        ('patients', '0002_patient_created_by_alter_patient_notes_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='activity_logs',
                    to='patients.content'
                )),
                ('patient', models.ForeignKey(
                    default=9,  
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='activity_logs',
                    to='patients.patient'
                )),
            ],
        ),
        migrations.DeleteModel(
            name='PatientActivityLog',
        ),
    ]
