# Generated by Django 6.0.8 on 2026-09-25 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_logs', '0003_activitylog_delete_patientactivitylog'),
        ('patients', '0003_rename_linked_patient_content_patient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='patients.patient'),
        ),
    ]
