# Generated by Django 6.0.8 on 2026-09-02 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_activity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='PatientLog',
        ),
    ]
