# Generated by Django 6.0.8 on 2026-09-14 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_activity', '0002_patientactivitylog_delete_patientlog'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientactivitylog',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='patientactivitylog',
            name='action',
            field=models.CharField(max_length=50),
        ),
    ]
