# Generated by Django 6.0.8 on 2026-09-25 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_activity', '0003_patientactivitylog_patient_and_more'),
        ('patients', '0002_patient_created_by_alter_patient_notes_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patientactivitylog',
            name='role',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='patientactivitylog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patientactivitylog',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted')], max_length=10),
        ),
        migrations.AlterField(
            model_name='patientactivitylog',
            name='patient',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to='patients.patient'),
            preserve_default=False,
        ),
    ]
