# Generated by Django 6.0.8 on 2026-09-25 17:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_created_by_alter_patient_notes_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='linked_patient',
            new_name='patient',
        ),
        migrations.RemoveField(
            model_name='content',
            name='file_path',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='created_by',
        ),
        migrations.AddField(
            model_name='content',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='patient_notes/audio/'),
        ),
        migrations.AddField(
            model_name='content',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='content',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='content',
            name='topic',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='patient',
            name='notes',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='stage',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
