# Generated by Django 6.0.8 on 2026-10-05 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_rename_linked_patient_content_patient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='patient_notes/images/'),
        ),
        migrations.AddField(
            model_name='content',
            name='stage',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='content',
            name='translation_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translations', to='patients.content'),
        ),
        migrations.AlterField(
            model_name='content',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contents', to='patients.patient'),
        ),
    ]
